Repository zenitheesc/frameworkd, pull requests merged in 2022-03, with the labels that each got.

#21 Feature/auto setup
  src/classes/routine-service-proxy/routine-service-proxy.cpp
  src/classes/service-handler/service-handler.cpp
  src/classes/service-proxy/service-proxy.cpp
  src/classes/service-proxy/service-proxy.hpp
  src/classes/static-service-proxy/static-service-proxy.cpp
Labels: enhancement

#22 Feature/static dbus
  cmake/SourcesAndHeaders.cmake
Labels: bug

#23 Feature/software integration
  CMakeLists.txt
  src/classes/daemon/daemon.cpp
  src/utilities/config-handler/config-handler.cpp
  src/utilities/config-handler/config-handler.hpp
Labels: enhancement

#24 Utils/examples
  examples/PING.json
  examples/PONG.json
  examples/configModel.json
  examples/ping.cpp
  examples/pong.cpp
Labels: documentation, enhancement
